### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'assets\sprites'

### ISSUE THREAD

**Issue by VanndyKun** [mehmetemineker/flappy-bird#3]
File "c:\Test\flappy-bird\main.py", line 22, in <module>
assets.load_sprites()
File "c:\Test\flappy-bird\assets.py", line 10, in load_sprites
for file in os.listdir(path):
^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'assets\sprites'

Hello i got install everything but in vs code it's still display tha't i don't know how to fix it i am a beginner pls help

**Comment by mehmetemineker** [comment]
Hello, it may be caused by Windows or VS Code. As a workaround, you can try to give the full path. You can try to change the parts on lines 9 and 19 in the assets.py file. 

https://towardsthecloud.com/get-absolute-path-python

**Comment by VanndyKun** [comment]
> Hello, it may be caused by Windows or VS Code. As a workaround, you can try to give the full path. You can try to change the parts on lines 9 and 19 in the assets.py file.
> 
> https://towardsthecloud.com/get-absolute-path-python

Thanks sir you now it has solved
